### ISSUE TITLE
NOT running the scheduled event in a workflow

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-coffeehouse#15]
The scheduled event in a workflow sometimes doesn't run.

```yaml
name: Update contributor list on README.md

on:
#  push:
#  pull_request:
  schedule:
#    * is a special character in YAML so you have to quote this string
#    “At 00:00 on Monday.”
#  - cron: '0 0 * * 1'
#    “At every 5th minute” for testing
#     - cron: '0/5 * * * *'
#    “At 00:00 Everyday.”
   - cron: '0 0 * * *'


jobs:
  contrib-readme-job:
    if: github.repository == 'cloud-barista/cb-coffeehouse'
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
```

No result for 00:00 today:
![image](https://user-images.githubusercontent.com/7975459/127245925-fcdf8caa-9799-4642-b081-d54d72af560e.png)
